### ISSUE TITLE
ArrayIndexOutOfBoundsException while adding random numbers to IntDoubleLinkedSet [HPPC-95]

### ISSUE THREAD

**Issue by dweiss** [carrotsearch/hppc#138]
Trying to benchmark the IntDoubleLinkedSet class to compare against trove's TIntHashSet, I have reduced my benchmark to a simple test class that adds 10 000 random int values to the set, after running into the following error:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -676084406
	at com.carrotsearch.hppc.IntDoubleLinkedSet.add(IntDoubleLinkedSet.java:185)
	at data.AddRandomNumbersToIntSet.main(AddRandomNumbersToIntSet.java:14)

I use OpenJDK 1.7.0_55 on x64 Linux.

---
Issue: HPPC-95 (migrated from JIRA), created by Andre Bogus, resolved Jul 11 2014
Attachments: [AddRandomNumbersToIntSet.java](https://carrotsearch.github.io/jira-archive-public/attachments/hppc/HPPC-95/AddRandomNumbersToIntSet.java)

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

Run with assertions enabled. Then you'll see what the problem is:

```Java
java.lang.AssertionError: Double linked set supports values >= 0 only.
```


You are using a very specific set, one that has constant-time operation costs, including clear(), but won't work for negative values. The set you're probably looking for is called IntOpenHashSet.

**Comment by dweiss** [comment]
Comment by Andre Bogus (migrated from JIRA)

Thanks. I've updated my benchmark to use IntOpenHashSet. I'm impressed in that it has comparable performance to trove for random values, however trove benefits from patterns in the values, which can speed it up to be 30-50% faster than IntOpenHashSet.

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)

It should be (always was) faster than Trove. Benchmarks are a tricky thing in Java; make sure you actually run c2-compiled, warmed-up code. Try fastutil as well – HPPC is on par with that implementation.

**Comment by dweiss** [comment]
Comment by Andre Bogus (migrated from JIRA)

I can assure you that with my benchmarks there is no further compilation during measurement. I have taken the benchmarks from a use case we have, running on a 16-core Xeon with 96G RAM, Debian Wheezy and OpenJDK 1.7.0_55. Perhaps the non-standard hardware makes for the differences in results?

**Comment by dweiss** [comment]
Comment by Dawid Weiss (@dweiss) (migrated from JIRA)


Hard to say without looking at the code, really. If you can post it I may be able to provide some insight into what you're seing. You may be right – memory access patterns do play a role, sure. Like I said – the code typically explains more about the behavior than wild guessing.
